### ISSUE TITLE
Unable to run without sudo when installed globally

### ISSUE THREAD

**Issue by lmakarov** [staempfli/magento2-code-generator#11]
`mg2-codegen` is part of a local development toolbox I maintain, but I'm not using it daily or familiar with it much, so please forgive my ignorance.

I noticed `mg2-codegen` won't run as a regular user when installed globally (`/usr/local/bin`). It invokes a self-update process, which attempts to write to `/usr/local/bin/` and fails.

**Installation**

```
sudo curl -sSL https://github.com/staempfli/magento2-code-generator/releases/download/1.10.1/mg2-codegen.phar -o /usr/local/bin/mg2-codegen
sudo chmod +x /usr/local/bin/mg2-codegen
```

**Running as a regular user**

```
mg2-codegen --version

Fatal error: Uncaught Humbug\SelfUpdate\Exception\FilesystemException: The current phar file is not writeable and cannot be replaced: /usr/local/bin/mg2-codegen. in phar:///usr/local/bin/mg2-codegen/vendor/padraic/phar-updater/src/Updater.php:430
Stack trace:
#0 phar:///usr/local/bin/mg2-codegen/vendor/padraic/phar-updater/src/Updater.php(101): Humbug\SelfUpdate\Updater->setLocalPharFile('/usr/local/bin/...')
#1 phar:///usr/local/bin/mg2-codegen/src/Staempfli/Mg2CodeGenerator/Command/SelfUpdateCommand.php(35): Humbug\SelfUpdate\Updater->__construct(NULL, false, 'github')
#2 phar:///usr/local/bin/mg2-codegen/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Application.php(57): Staempfli\Mg2CodeGenerator\Command\SelfUpdateCommand->__construct('self-update')
#3 phar:///usr/local/bin/mg2-codegen/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Application.php(68): Staempfli\UniversalGenerator\Application->loadGeneratorCommands()
#4 phar:///usr/local/bin/mg2-codegen/bin/mg2-c in phar:///usr/local/bin/mg2-codegen/vendor/padraic/phar-updater/src/Updater.php on line 430
```

**Running with sudo**

```
sudo mg2-codegen --version
mg2-codegen 1.10.1
```

**Expected results**

Be able to run `mg2-codegen`  (installed globally) as a regular users (without sudo).

**Comment by jalogut** [comment]
Hi @lmakarov 

Do you have this problem for all commands or only for `--version` and `self-update`?

**Comment by lmakarov** [comment]
@jalogut any command. `mg2-codegen` won't start at all if the executable is not writable by the current user.

```
docker@cli:/var/www$ mg2-codegen

Fatal error: Uncaught Humbug\SelfUpdate\Exception\FilesystemException: The current phar file is not writeable and cannot be replaced: /usr/local/bin/mg2-codegen. in phar:///usr/local/bin/mg2-codegen/vendor/padraic/phar-updater/src/Updater.php:430
Stack trace:
#0 phar:///usr/local/bin/mg2-codegen/vendor/padraic/phar-updater/src/Updater.php(101): Humbug\SelfUpdate\Updater->setLocalPharFile('/usr/local/bin/...')
#1 phar:///usr/local/bin/mg2-codegen/src/Staempfli/Mg2CodeGenerator/Command/SelfUpdateCommand.php(35): Humbug\SelfUpdate\Updater->__construct(NULL, false, 'github')
#2 phar:///usr/local/bin/mg2-codegen/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Application.php(57): Staempfli\Mg2CodeGenerator\Command\SelfUpdateCommand->__construct('self-update')
#3 phar:///usr/local/bin/mg2-codegen/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Application.php(68): Staempfli\UniversalGenerator\Application->loadGeneratorCommands()
#4 phar:///usr/local/bin/mg2-codegen/bin/mg2-c in phar:///usr/local/bin/mg2-codegen/vendor/padraic/phar-updater/src/Updater.php on line 430
```

**Comment by jalogut** [comment]
Ok, I will have a look. In the meantime you can give `mg2-codegen` write permissions for all users. That way, you can execute it without sudo.

**Comment by lmakarov** [comment]
Looks like the updater tries to delete the file first, so it needs write permissions on the parent directory:

```
docker@cli:/var/www$ sudo chmod ugo+w /usr/local/bin/mg2-codegen
docker@cli:/var/www$ mg2-codegen

Fatal error: Uncaught Humbug\SelfUpdate\Exception\FilesystemException: The directory is not writeable: /usr/local/bin. in phar:///usr/local/bin/mg2-codegen/vendor/padraic/phar-updater/src/Updater.php:454
...
```

**Comment by jalogut** [comment]
Hi @lmakarov 

Thanks for the info. Sure that will help other people with same problem. Then I'll close the issue if you do not mind.

**Comment by HOSTED-POWER** [comment]
Same problem here, never saw this problem with other phar files
